spring:
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        show_sql: true
  error:
    include-message: always

cashmanager.security.rsa:
  access-public-key: classpath:certs/access-public-key.pem
  access-private-key: classpath:certs/access-private-key.pem
  refresh-public-key: classpath:certs/refresh-public-key.pem
  refresh-private-key: classpath:certs/refresh-private-key.pem

logging:
  level:
    org:
      springframework: INFO
auth-service-property:
  isuer: "self"
  minutes-amount: 60