spring:
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  error:
    include-message: always
  boot:
    admin:
      mail:
        from: ${EMAIL}
  mail:
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL}
    port: 465
    host: smtp.gmail.com
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
cashmanager.security.rsa:
  access-public-key: classpath:certs/access-public-key.pem
  access-private-key: classpath:certs/access-private-key.pem
  refresh-public-key: classpath:certs/refresh-public-key.pem
  refresh-private-key: classpath:certs/refresh-private-key.pem
logging:
  level:
    org:
      springframework: INFO
cashmanager:
  security:
    jwt:
      issuer: "self"
      refresh-token-minutes-amount: 60
      access-token-minutes-amount: 15