spring:
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8000
  error:
    include-message: always

rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

logging:
  level:
    org:
      springframework: INFO