name: Checkstyle
on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Run Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: sun_checks.xml
          reporter: github-pr-review
          level: warning
